### ISSUE TITLE
New genotype file format

### ISSUE THREAD

**Issue by justinbois** [justinbois/fish-activity#1]
CSV file, with header having CSV genotype names *only*, and columns below have fish numbers with the corresponding genotype.

Update `parse` functions to handle this.

**Comment by justinbois** [comment]
I'm thinking that it would be good to also include an `omit` column in every genotype file. This helps prevent errors. It forces the user to make sure that all fish are accounted for. Furthermore, after checking for possibly dead or developmentally anomalous fish, the user can then move a fish to the `omit` column of the genotype file.

The `validate` module will check for this and alert the user if the `omit` column is missing. The `parse` module will infer omissions if the `omit` column is absent, but display a warning that it is doing so.

**Comment by grigorios-oikonomou** [comment]
This is a good idea. There are two issues though:
1) It might be annoying for people to have to look through all their old genotype files to find which numbers are missing,
2) It would make the new genotype files slightly incompatible with our matlab scripts that don't have such functionality (I say slightly cause there are easy ways to ignore the last column of the genotype file).

So perhaps don't make it mandatory to have all fish accounted for; just give a warning/notification when some are missing. That way people can use the future from now on, but not have to revamp their old genotype files.

**Comment by justinbois** [comment]
Already implemented. Backward compatibility currently gives warning, not failure.

We may revisit and issue deprecation warning.

Closing.
