### ISSUE TITLE
Parse by day/night

### ISSUE THREAD

**Issue by grigorios-oikonomou** [justinbois/fish-activity#13]
We commonly quantify the data for each fish by its activity/sleep/bout number/bout length/latency etc, per day or night. For example: "On night 5 of development mutants slept an average of x min/hr, while controls slept an average of y min/hr. See scatterplot."

Is this something I can easily get with pandas from the current parser, or does it require a new  modality for the fishact.parse function?

**Comment by justinbois** [comment]
This can easily be done with Pandas. Here are a couple examples (assuming you have imported `fishact`, `np`, and `matplotlib.pyplot as plt`, etc.).

Make an ECDF of bout lengths for all bouts contained entirely in night 6 for wild type
```python
df = fishact.parse.load_activity('sample_activity_file.csv', 
                                 genotype_fname='sample_genotype_file.txt')

df_bout = fishact.summarize.bouts(df)

# Slice out bouts entirely in night 6
inds = ~(df_bout['light_start']) & ~(df_bout['light_end']) \
        & (df_bout['day_start'] == 6) & (df_bout['day_end'] == 6)  \
        & (df_bout['genotype'] == 'wt')

# Make ECDF
plt.plot(*fishact.visualize.ecdf(df_bout.loc[inds, 'bout_length']), '.')

# Compute mean bout length
np.mean(df_bout.loc[inds, 'bout_length'])
```

Compute mean activity with during day 7 with bootstrapped error bar:
```python
df = fishact.parse.load_activity('sample_activity_file.csv', 
                                 genotype_fname='sample_genotype_file.txt')

# Slice out day 7 for wild type
inds = (df['light']) & (df['day'] == 7) & (df['genotype'] == 'wt')

# Extract activities
activities = df.loc[inds, 'activity'].values

# Compute mean
mean_activity = np.mean(activities)

# Bootstrap confidence interval (can just use SEM here, but this is for fun)
bs_reps = [np.mean(np.random.choice(activities, replace=True, size=len(activities))) 
           for _ in range(10000)]
conf_int = np.percentile(bs_reps, [2.5, 97.5])
```

Note that we will no longer be using `'day'`, but will use `'light_cycle'`, as per #10. Latency is also not yet implemented, included in #4.

I am closing this issue. For special cases that you want convenience functions to output, use separate issues with the enhancement tag.
