### ISSUE TITLE
Have "center" as default alignment

### ISSUE THREAD

**Issue by grigorios-oikonomou** [justinbois/fish-activity#5]
When graphing data I think it would be best to have the data point for each hour (you used a fancy word for this that I do not remember) at the center of the bin. This way at transitions between light and dark, it will be clear where the data point belongs.

**Comment by justinbois** [comment]
The feature (where the time associated with a given time interval is at the center of the interval) was already present in visualization and is now the default.

@grigorios-oikonomou, do you want this also to be how the time points in the DataFrames are set up? Right now, the time point is the left of the interval, i.e., what the `start` field in the original data file is.

**Comment by grigorios-oikonomou** [comment]
Awesome!

I don't think it's necessary to have it in the dataframe as well; it might become confusing actually.

**Comment by justinbois** [comment]
Ok, DataFrames will retain left-alignment with the time interval and activity.
