### ISSUE TITLE
flag for skipping confidence interval calculation/visualization

### ISSUE THREAD

**Issue by grigorios-oikonomou** [justinbois/fish-activity#6]
It would be useful when building the summary graph to be able to skip the calculation/visualization of the confidence intervals. Sometimes we have enough genotypes (4 or more) that it gets too cluttered; also useful for speed.

**Comment by justinbois** [comment]
Already implemented. Use the `--confint 0` flag for the `fishviz.py` executable. If you are calling the function `fishact.visualize.summary()`, use the `confint=False` kwarg.

**Comment by grigorios-oikonomou** [comment]
Sorry, I don't get it.

If I type:
> fishviz.py 170324_6A_6B.csv 170324_6A_genotype_2.txt   --window 60 --summary 

I get the summary graph with the confidence intervals.

If I type 
> fishviz.py 170324_6A_6B.csv 170324_6A_genotype_2.txt   --window 60  --summary --confint 0

I get exactly the same graph (confidence intervals still there).

**Comment by justinbois** [comment]
Do `git pull` both tsplot and fish-activity. It works on my machine. If it's still not working, reopen the issue.

**Comment by grigorios-oikonomou** [comment]
Works perfect; I had not done the git pull for the tsplot.
