### ISSUE TITLE
Sleep bug?

### ISSUE THREAD

**Issue by grigorios-oikonomou** [justinbois/fish-activity#9]
When I try to graph sleep using
> fishviz.py 170324_6A_6B.csv 170324_6A_genotype_2.txt  --window 60 --sleep 

I get the same graph as when I plot activity using

> fishviz.py 170324_6A_6B.csv 170324_6A_genotype_2.txt  --window 60

The only difference is in the Y axis labels

![bokeh_plot 8](https://cloud.githubusercontent.com/assets/26811651/24571927/7b5a1268-1629-11e7-86f6-a90b484f1716.png)

![bokeh_plot 7](https://cloud.githubusercontent.com/assets/26811651/24571891/40623230-1629-11e7-8cc1-9703217efa51.png)

**Comment by justinbois** [comment]
This was already fixed. Did you `git pull` both this and tsplot?

Also, the titles already show a problem with the parsing of the genotype file. You're missing stuff because of the deleted closed parentheses. I'll address in #1 .

**Comment by grigorios-oikonomou** [comment]
I git pull for both the tsplot/ and the fish-activity. Verified by getting "Already up-to-date." Still same issue with sleep. The other issue (with confint) was fixed once I git pulled.

**Comment by justinbois** [comment]
Apologies. Now fixed. (@grigorios-oikonomou, whenever I fix, just `git pull` both tsplot and fish-activity again.)

**Comment by grigorios-oikonomou** [comment]
Awesome! Works great! 
Only change is the y axis label should read "minutes" instead of "seconds".

I will keep git pulling as you go along :)

**Comment by justinbois** [comment]
Axis label fixed.
